### ISSUE TITLE
jekyll build fails with new x86 models

### ISSUE THREAD

**Issue by rubo77** [ffnord/startseite#15]
When you try to build the startpage, [this line](https://github.com/ffnord/startseite/blob/master/_plugins/firmwares.rb#L7) doesn't fit to the new x86 images:

    HWREV_REGEX = /^(.+)-(v|rev-)([\w\.]+)$/

When it tries to analyze http://gluon.ffki.de/firmware/stable/sysupgrade/, jekyll crashes with

    jekyll 2.2.0 | Error:  comparison of String with nil failed

Or maybe the file `stable.manifest` is the problem?

**Comment by rubo77** [comment]
Workaround
----

as long as the site doesn't build you can update your page temporarily with 

    sed 's/-0\.6/-0\.7/g' _site/firmware.html -i

**Comment by rubo77** [comment]
When I call `jekyll build --trace` I get more info:

    part stable.manifest
    /opt/ffki-startseite/_plugins/firmwares.rb:153:in `sort_by': comparison of NilClass with String failed (ArgumentError)
	from /opt/ffki-startseite/_plugins/firmwares.rb:153:in `block (2 levels) in generate'
	from /opt/ffki-startseite/_plugins/firmwares.rb:152:in `map'
	from /opt/ffki-startseite/_plugins/firmwares.rb:152:in `block in generate'
	from /opt/ffki-startseite/_plugins/firmwares.rb:151:in `each'
	from /opt/ffki-startseite/_plugins/firmwares.rb:151:in `generate'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:243:in `block in generate'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:242:in `each'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:242:in `generate'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:42:in `process'
	from /usr/lib/ruby/vendor_ruby/jekyll/command.rb:53:in `process_site'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:50:in `build'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:33:in `process'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:35:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:22:in `program'
	from /usr/bin/jekyll:18:in `<main>'

If I comment out this line: https://github.com/ffnord/startseite/blob/master/_plugins/firmwares.rb#L99 I get no error, but also no firmware content, so the error seems to be in that function
